# Generated by Django 5.0.2 on 2025-12-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='planner.day')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('hourslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.hourslot')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
