# Generated by Django 5.0.2 on 2025-12-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_taskattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
