# Generated by Django 5.0.2 on 2026-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='urgencia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Urgente'), (2, 'Urgente'), (3, 'Normal'), (4, 'Baja')], default=3),
        ),
    ]
