# Generated by Django 5.0.2 on 2026-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_subchecklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='urgencia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muy Urgente'), (2, 'Urgente'), (3, 'Normal'), (4, 'Baja'), (5, 'Informativo')], default=3),
        ),
        migrations.AlterField(
            model_name='subchecklistitem',
            name='text',
            field=models.TextField(),
        ),
    ]
